Bubble: Bubble.o BubbleMain.o
	gcc -o Bubble Bubble.o BubbleMain.o
Bubble.o: Bubble.c
	gcc -c Bubble.c 
BubbleMain.o: BubbleMain.c
	gcc -c BubbleMain.c

clean:
	rm -rf *.o
	rm -rf *.gch
	rm -rf Bubble